url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
copyright-year: 2015

sections-enabled:
  - services
  - portfolio_grid
  - about
  - team
  - clients
  - contact

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

header:
  heading: Welcome To Our Studio!
  subheading: It's Nice To Meet You
  action: Tell Me More
  action-id: Services
  background-image: ../img/header-bg.jpg

services:
  name: Services
  navigation: yes
  heading: Services
  subheading: Lorem ipsum dolor sit amet consectetur.
  list:
    - name: E-Commerce
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
      fa-class: fa-shopping-cart
    - name: Responsive Design
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
      fa-class: fa-laptop
    - name: Web Security
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
      fa-class: fa-lock

portfolio_grid:
  name: Portfolio
  navigation: yes
  heading: Portfolio
  subheading: Lorem ipsum dolor sit amet consectetur.

about:
  name: About
  navigation: yes
  heading: About
  subheading: Lorem ipsum dolor sit amet consectetur.
  timeline:
    - name: Our Humble Beginnings
      when: 2009-2011
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/1.jpg
    - name: An Agency is Born
      whwn: March 2011
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/2.jpg
    - name: Transition to Full Service
      whwn: December 2012
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/3.jpg
    - name: Phase Two Expansion
      when: July 2014
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/4.jpg

team:
  name: Team
  navigation: yes
  heading: Our Amazing Team
  subheading: Lorem ipsum dolor sit amet consectetur.
  footer: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.

  # Team names, titles and social links
  people:
  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Larry Parker
    pic: 2
    position: Lead Marketer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Diana Petersen
    pic: 3
    position: Lead Developer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

clients:
  name: Clients
  navigation: no
  list:
    - logo: img/logos/envato.jpg
    - logo: img/logos/designmodo.jpg
    - logo: img/logos/themeforest.jpg
    - logo: img/logos/creative-market.jpg

contact:
  name: Contact
  navigation: yes
  heading: Contact Us
  contact-subheading: Lorem ipsum dolor sit amet consectetur.
  background-image: ../img/map-image.png

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

quick-links:
  - title: Privacy Policy
    url: #
  - title: Terms of Use
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
