# Site settings
#title: Awesome Title
#email: your-email@domain.com
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
#title: Awesome Title
#email: your-email@domain.com
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/
title: Fieldthings
email: info@fieldthings.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fieldthings.com" # the base hostname & protocol for your site
#twitter_username: fieldthings
#github_username:  fieldthings
copyright-year: 2015

# Build settings
markdown: kramdown
permalink: pretty

sections-enabled:
  - services
  - portfolio_grid
  - about
  - team
  - clients
  - contact

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

header:
  heading: High School and Middle School<br> Football is changing.
  subheading: More efficient, connected and engaged than ever before.
  action: Tell Me More
  action-id: Services
#  background-image: ../img/header-bg.jpg
  background-image: ../img/header-bg-football.jpg


services:
  name: Services
  navigation: yes
  heading: Services
  subheading: Lorem ipsum dolor sit amet consectetur.
  list:
    - name: E-Commerce
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
      fa-class: fa-shopping-cart
    - name: Responsive Design
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
      fa-class: fa-laptop
    - name: Web Security
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
      fa-class: fa-lock

portfolio_grid:
  name: Portfolio
  navigation: yes
  heading: Portfolio
  subheading: Lorem ipsum dolor sit amet consectetur.

about:
  name: About
  navigation: yes
  heading: About
  subheading: Lorem ipsum dolor sit amet consectetur.
  timeline:
    - name: Our Humble Beginnings
      when: 2009-2011
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/1.jpg
    - name: An Agency is Born
      whwn: March 2011
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/2.jpg
    - name: Transition to Full Service
      whwn: December 2012
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/3.jpg
    - name: Phase Two Expansion
      when: July 2014
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!
      pic: img/about/4.jpg

team:
  name: Team
  navigation: yes
  heading: The Team
  subheading: We are changing High School and Middle School Football.
  footer: We benefit from decades of experience ranging from mobile and web applications development, distributed video transcoding, Internet marketing, Department of Defense contracting, hardware and video games.
  # Team names, titles and social links
  people:
#    - name: Kay Garland
#      pic: 1
#      position: Lead Designer
#      social:
#        - title: twitter
#          url: #
#        - title: facebook
#          url: #
#        - title: stack-overflow
#          url: #
#
#    - name: Larry Parker
#      pic: 2
#      position: Lead Marketer
#      social:
#        - title: twitter
#          url: #
#        - title: facebook
#          url: #
#        - title: linkedin
#          url: #
#
#    - name: Diana Petersen
#      pic: 3
#      position: Lead Developer
#      social:
#        - title: twitter
#          url: #
#        - title: facebook
#          url: #
#        - title: google-plus
#          url: #
    - name: Jim Williams
      pic: jwilliams
      position: Co-Founder & Cheif Executive Officer
      social:
        - title: twitter
          url: http://twitter.com/ # TODO
        - title: linkedin
          url: https://www.linkedin.com/in # TODO
    - name: Ryan Ovrevik
      pic: rovrevik
      position: Co-Founder & President
      social:
        - title: twitter
          url: http://twitter.com/rovrevik
        - title: linkedin
          url: https://www.linkedin.com/in/rovrevik

clients:
  name: Clients
  navigation: no
  list:
    - logo: img/logos/envato.jpg
    - logo: img/logos/designmodo.jpg
    - logo: img/logos/themeforest.jpg
    - logo: img/logos/creative-market.jpg

contact:
  name: Contact
  navigation: yes
  heading: Contact Us
  contact-subheading: Lorem ipsum dolor sit amet consectetur.
  background-image: ../img/map-image.png

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll
  - title: twitter
    url: http://twitter.com/fieldthings
  - title: facebook
    url: http://www.facebook.com/Fieldthings
  - title: bitbucket
    url: http://bitbucket.org/fieldthings
  - title: github
    url: https://github.com/fieldthings

quick-links:
  - title: Privacy Policy
    url: #
  - title: Terms of Use
    url: #

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210
  - line: Alpharetta, Georgia 30004
