# Site settings
#title: Awesome Title
title: Fieldthings
#email: your-email@domain.com
email: info@fieldthings.com
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#url: https://rovrevik.github.io # the base hostname & protocol for your site
url: "http://www.fieldthings.com" # the base hostname & protocol for your site
#baseurl: /agency-jekyll-theme-redux
baseurl: "" # the subpath of your site, e.g. /blog/
#twitter_username: fieldthings
#github_username:  fieldthings
copyright-year: 2015

collections:
  solution:
  timeline:
  team:
  portfolio:
  services:

# Build settings
markdown: kramdown
permalink: pretty
